### ISSUE TITLE
[FEAT]: Favicon is missing

### ISSUE THREAD

**Issue by akashpatel25** [ImBIOS/qwiktober-2022#111]
### Clear and concise description of the problem

Favicon is not added in your website.

### Suggested solution

I can add it please assign me that task.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ImBIOS/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/ImBIOS/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by ImBIOS** [comment]
It is a collection of websites. What website do you mean? If it's the landing page, this is deliberately made so to show this website using the Qwik City framework.
