### ISSUE TITLE
[FEAT]: Add Favicon in your website.

### ISSUE THREAD

**Issue by akashpatel25** [ImBIOS/qwiktober-2022#120]
### Clear and concise description of the problem

Favicon is missing in your website. Please assign it to me. I'll do that.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ImBIOS/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/ImBIOS/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by ImBIOS** [comment]
@akashpatel25 This issue description is not concise. Where is the part that is missing the favicon that you want to add?
