### ISSUE TITLE
I want to fix Explore button 

### ISSUE THREAD

**Issue by omriattiya** [ImBIOS/qwiktober-2022#55]
### Clear and concise description of the problem

the explore button looks bad - weird color and the clickable area is only the text. 

### Suggested solution

I will change the color and make the button clickable area all over the button

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ImBIOS/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/ImBIOS/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by ImBIOS** [comment]
Welcome! It's yours 😁🧑‍💻
