### ISSUE TITLE
Auto add contributor to landing page

### ISSUE THREAD

**Issue by ImBIOS** [ImBIOS/qwiktober-2022#71]
### Clear and concise description of the problem

It will be nice when we not add manually contributor to our landing page

### Suggested solution

We can use GitHub API (https://api.github.com/repos/ImBIOS/qwiktober-2022/contributors) to fetch the contributor list then render it as card group of contributors.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ImBIOS/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/ImBIOS/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by Vinitvh** [comment]
Hi, I would like to work on this.

**Comment by ImBIOS** [comment]
Sorry, @Vinitvh I already took it. you can add dark mode #72
